"""add generated_plans table

Revision ID: 7b240a57e40e
Revises: 
Create Date: 2026-05-14 15:33:49.656532

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '7b240a57e40e'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('generated_plans',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('plan_type', sa.String(length=20), nullable=False),
    sa.Column('plan_data', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('preferences', sa.String(length=500), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_generated_plans_plan_type'), 'generated_plans', ['plan_type'], unique=False)
    op.create_index(op.f('ix_generated_plans_user_id'), 'generated_plans', ['user_id'], unique=False)
    
    # Create blood_group_enum type manually if it doesn't exist
    blood_group_enum = postgresql.ENUM('A_pos', 'A_neg', 'B_pos', 'B_neg', 'AB_pos', 'AB_neg', 'O_pos', 'O_neg', name='blood_group_enum')
    blood_group_enum.create(op.get_bind(), checkfirst=True)
    
    op.add_column('users', sa.Column('blood_group', sa.Enum('A_pos', 'A_neg', 'B_pos', 'B_neg', 'AB_pos', 'AB_neg', 'O_pos', 'O_neg', name='blood_group_enum'), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'blood_group')
    op.drop_index(op.f('ix_generated_plans_user_id'), table_name='generated_plans')
    op.drop_index(op.f('ix_generated_plans_plan_type'), table_name='generated_plans')
    op.drop_table('generated_plans')
    # ### end Alembic commands ###
