"""add weight_kg to daily_metrics

Revision ID: e8ed7bb985de
Revises: 817307ace161
Create Date: 2026-05-14 16:22:11.651904

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e8ed7bb985de'
down_revision: Union[str, None] = '817307ace161'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('daily_metrics', sa.Column('weight_kg', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('daily_metrics', 'weight_kg')
    # ### end Alembic commands ###
